/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.aitor.ra5.vista;

/**
 *
 * @author aitor
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pan_aes = new javax.swing.JPanel();
        aes_tf_file = new javax.swing.JTextField();
        aes_ptf_pswd = new javax.swing.JPasswordField();
        aes_rbut_enc = new javax.swing.JRadioButton();
        aes_rbut_dec = new javax.swing.JRadioButton();
        aes_but_file = new javax.swing.JButton();
        aes_checkb_pswd = new javax.swing.JCheckBox();
        aes_but_execute = new javax.swing.JButton();
        aes_checkb_keysize = new javax.swing.JCheckBox();
        aes_combob_keysize = new javax.swing.JComboBox<>();
        pan_hash = new javax.swing.JPanel();
        hash_rbut_text = new javax.swing.JRadioButton();
        hash_rbut_file = new javax.swing.JRadioButton();
        hash_tf_file = new javax.swing.JTextField();
        hash_but_file = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        hash_tp_msg = new javax.swing.JTextPane();
        hash_but_execute = new javax.swing.JButton();
        hash_combob_alg = new javax.swing.JComboBox<>();
        pan_rsa = new javax.swing.JPanel();
        rsa_tf_file = new javax.swing.JTextField();
        rsa_ptf_pswd = new javax.swing.JPasswordField();
        rsa_rbut_enc = new javax.swing.JRadioButton();
        rsa_rbut_dec = new javax.swing.JRadioButton();
        rsa_but_file = new javax.swing.JButton();
        rsa_checkb_pswd = new javax.swing.JCheckBox();
        rsa_but_execute = new javax.swing.JButton();
        rsa_key_type = new javax.swing.JLabel();
        rsa_but_key = new javax.swing.JButton();
        rsa_tf_key = new javax.swing.JTextField();
        pan_key = new javax.swing.JPanel();
        key_tf_name = new javax.swing.JTextField();
        key_but_dir = new javax.swing.JButton();
        key_but_execute = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        key_tf_file = new javax.swing.JTextField();
        key_checkb_dir = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_info = new javax.swing.JTextArea();
        pan_tools = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu_tools = new javax.swing.JMenu();
        menu_hash = new javax.swing.JMenuItem();
        menu_aes = new javax.swing.JMenuItem();
        menu_rsa_stuff = new javax.swing.JMenu();
        menu_rsa = new javax.swing.JMenuItem();
        menu_keys = new javax.swing.JMenuItem();

        pan_aes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pan_aes.add(aes_tf_file, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 260, -1));
        pan_aes.add(aes_ptf_pswd, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 260, -1));

        aes_rbut_enc.setSelected(true);
        aes_rbut_enc.setText("Encryption");
        pan_aes.add(aes_rbut_enc, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        aes_rbut_dec.setText("Decryption");
        pan_aes.add(aes_rbut_dec, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        aes_but_file.setText("Choose file");
        aes_but_file.setActionCommand("aes_but_file");
        pan_aes.add(aes_but_file, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, -1, -1));

        aes_checkb_pswd.setSelected(true);
        aes_checkb_pswd.setText("Password");
        pan_aes.add(aes_checkb_pswd, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        aes_but_execute.setText("Execute");
        aes_but_execute.setActionCommand("aes_but_execute");
        pan_aes.add(aes_but_execute, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 290, -1, -1));

        aes_checkb_keysize.setText("Key Size");
        pan_aes.add(aes_checkb_keysize, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));

        aes_combob_keysize.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "128", "192", "256" }));
        aes_combob_keysize.setEnabled(false);
        pan_aes.add(aes_combob_keysize, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, -1, -1));

        pan_hash.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        hash_rbut_text.setText("Text");
        hash_rbut_text.setActionCommand("hash_rbut_text");
        pan_hash.add(hash_rbut_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        hash_rbut_file.setText("File");
        hash_rbut_file.setActionCommand("hash_rbut_file");
        pan_hash.add(hash_rbut_file, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));
        pan_hash.add(hash_tf_file, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 240, -1));

        hash_but_file.setText("Choose from Files");
        hash_but_file.setActionCommand("hash_but_file");
        pan_hash.add(hash_but_file, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 130, -1));

        jScrollPane2.setViewportView(hash_tp_msg);

        pan_hash.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 420, 180));

        hash_but_execute.setText("Execute");
        hash_but_execute.setActionCommand("hash_but_execute");
        pan_hash.add(hash_but_execute, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 310, -1, -1));

        hash_combob_alg.setMaximumRowCount(50);
        pan_hash.add(hash_combob_alg, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, 130, -1));

        pan_rsa.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pan_rsa.add(rsa_tf_file, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 260, -1));
        pan_rsa.add(rsa_ptf_pswd, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 260, -1));

        rsa_rbut_enc.setSelected(true);
        rsa_rbut_enc.setText("Encryption");
        pan_rsa.add(rsa_rbut_enc, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        rsa_rbut_dec.setText("Decryption");
        pan_rsa.add(rsa_rbut_dec, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        rsa_but_file.setText("Choose file");
        rsa_but_file.setActionCommand("rsa_but_file");
        pan_rsa.add(rsa_but_file, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, -1, -1));

        rsa_checkb_pswd.setSelected(true);
        rsa_checkb_pswd.setText("Password");
        pan_rsa.add(rsa_checkb_pswd, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        rsa_but_execute.setText("Execute");
        rsa_but_execute.setActionCommand("rsa_but_execute");
        pan_rsa.add(rsa_but_execute, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 290, -1, -1));

        rsa_key_type.setText("jLabel2");
        pan_rsa.add(rsa_key_type, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, -1));

        rsa_but_key.setText("Choose File");
        rsa_but_key.setActionCommand("rsa_but_key");
        pan_rsa.add(rsa_but_key, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 290, -1, -1));
        pan_rsa.add(rsa_tf_key, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 260, -1));

        pan_key.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pan_key.add(key_tf_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 260, -1));

        key_but_dir.setText("Choose file");
        key_but_dir.setActionCommand("key_but_dir");
        pan_key.add(key_but_dir, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, -1, -1));

        key_but_execute.setText("Execute");
        key_but_execute.setActionCommand("key_but_execute");
        pan_key.add(key_but_execute, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 290, -1, -1));

        jLabel2.setText("Name");
        pan_key.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, -1));
        pan_key.add(key_tf_file, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 260, -1));

        key_checkb_dir.setText("Custom Directory");
        pan_key.add(key_checkb_dir, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ta_info.setEditable(false);
        ta_info.setColumns(20);
        ta_info.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        ta_info.setRows(5);
        ta_info.setText("Esto es un texto de prueba\n");
        ta_info.setEnabled(false);
        jScrollPane1.setViewportView(ta_info);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, 630, 190));

        pan_tools.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout pan_toolsLayout = new javax.swing.GroupLayout(pan_tools);
        pan_tools.setLayout(pan_toolsLayout);
        pan_toolsLayout.setHorizontalGroup(
            pan_toolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 626, Short.MAX_VALUE)
        );
        pan_toolsLayout.setVerticalGroup(
            pan_toolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 376, Short.MAX_VALUE)
        );

        jPanel1.add(pan_tools, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 630, 380));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel1.setText("Resultado:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, -1, -1));

        jMenuBar1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        menu_tools.setText("Tools");
        menu_tools.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        menu_hash.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menu_hash.setText("Hash");
        menu_hash.setActionCommand("menu_hash");
        menu_tools.add(menu_hash);

        menu_aes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menu_aes.setText("AES");
        menu_aes.setActionCommand("menu_aes");
        menu_tools.add(menu_aes);

        menu_rsa_stuff.setText("RSA");

        menu_rsa.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menu_rsa.setText("RSA Operations");
        menu_rsa.setActionCommand("menu_rsa");
        menu_rsa_stuff.add(menu_rsa);

        menu_keys.setText("RSA Keys");
        menu_keys.setActionCommand("menu_keys");
        menu_rsa_stuff.add(menu_keys);

        menu_tools.add(menu_rsa_stuff);

        jMenuBar1.add(menu_tools);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 742, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 669, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton aes_but_execute;
    public javax.swing.JButton aes_but_file;
    public javax.swing.JCheckBox aes_checkb_keysize;
    public javax.swing.JCheckBox aes_checkb_pswd;
    public javax.swing.JComboBox<String> aes_combob_keysize;
    public javax.swing.JPasswordField aes_ptf_pswd;
    public javax.swing.JRadioButton aes_rbut_dec;
    public javax.swing.JRadioButton aes_rbut_enc;
    public javax.swing.JTextField aes_tf_file;
    public javax.swing.JButton hash_but_execute;
    public javax.swing.JButton hash_but_file;
    public javax.swing.JComboBox<String> hash_combob_alg;
    public javax.swing.JRadioButton hash_rbut_file;
    public javax.swing.JRadioButton hash_rbut_text;
    public javax.swing.JTextField hash_tf_file;
    public javax.swing.JTextPane hash_tp_msg;
    public javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JButton key_but_dir;
    public javax.swing.JButton key_but_execute;
    public javax.swing.JCheckBox key_checkb_dir;
    public javax.swing.JTextField key_tf_file;
    public javax.swing.JTextField key_tf_name;
    public javax.swing.JMenuItem menu_aes;
    public javax.swing.JMenuItem menu_hash;
    public javax.swing.JMenuItem menu_keys;
    public javax.swing.JMenuItem menu_rsa;
    private javax.swing.JMenu menu_rsa_stuff;
    public javax.swing.JMenu menu_tools;
    public javax.swing.JPanel pan_aes;
    public javax.swing.JPanel pan_hash;
    public javax.swing.JPanel pan_key;
    public javax.swing.JPanel pan_rsa;
    public javax.swing.JPanel pan_tools;
    public javax.swing.JButton rsa_but_execute;
    public javax.swing.JButton rsa_but_file;
    public javax.swing.JButton rsa_but_key;
    public javax.swing.JCheckBox rsa_checkb_pswd;
    public javax.swing.JLabel rsa_key_type;
    public javax.swing.JPasswordField rsa_ptf_pswd;
    public javax.swing.JRadioButton rsa_rbut_dec;
    public javax.swing.JRadioButton rsa_rbut_enc;
    public javax.swing.JTextField rsa_tf_file;
    public javax.swing.JTextField rsa_tf_key;
    public javax.swing.JTextArea ta_info;
    // End of variables declaration//GEN-END:variables
}
